### ISSUE TITLE
why video online not download

### ISSUE THREAD

**Issue by candrapersada** [persepolisdm/Persepolis-WebExtension#15]
why video online not download from chrome
URl http://videowing.gogoanime.to/index.php?vid=ongoing/lost_song_-_12.mp4

**Comment by JafarAkhondali** [comment]
@candrapersada By pressing `CTRL+U` you'll notice this is not actually an mp4 file. It's actually a HTML file which container Javascript codes to play the mp4 video, Currently this extension is not capable of downloading such content ( and this will not be implemented in future since it's against Google Store rules). However you can find URL of actual video by inspecting the source code and use that in DM
